from flask import Flask, request, jsonify
from flask_cors import CORS
import os

app = Flask(__name__)
CORS(app) 

# --- LINK TO THE TELEGRAM BOT'S DATABASE ---
DATA_DIR = "/data" if os.path.exists("/data") else "data"
APK_KEYS_FILE = os.path.join(DATA_DIR, "apk_keys.txt")          # Unused keys
APK_HISTORY_FILE = os.path.join(DATA_DIR, "apk_key_history.txt") # Master history

# --- FILE HELPERS ---
def read_apk_history():
    history = {}
    if not os.path.exists(APK_HISTORY_FILE): return history
    with open(APK_HISTORY_FILE, "r") as f:
        for line in f:
            parts = line.strip().split("|")
            if len(parts) >= 4:
                # Format: KEY|PLAN|CREATOR|STATUS
                history[parts[0]] = {"plan": parts[1], "creator": parts[2], "status": parts[3]}
    return history

def save_apk_history(history):
    with open(APK_HISTORY_FILE, "w") as f:
        for k, v in history.items():
            f.write(f"{k}|{v['plan']}|{v['creator']}|{v['status']}\n")

def read_active_apk_keys():
    keys = {}
    if not os.path.exists(APK_KEYS_FILE): return keys
    with open(APK_KEYS_FILE, "r") as f:
        for line in f:
            parts = line.strip().split("|")
            if len(parts) >= 2:
                keys[parts[0]] = parts[1]
    return keys

def save_active_apk_keys(keys):
    with open(APK_KEYS_FILE, "w") as f:
        for k, plan in keys.items():
            f.write(f"{k}|{plan}\n")

@app.route('/verify-key', methods=['POST'])
def verify_key():
    print("\n" + "="*30)
    print(">>> NEW ANDROID LOGIN ATTEMPT <<<")
    
    data = request.get_json(force=True, silent=True)
    if not data:
        return jsonify({"status": "error", "message": "Invalid data format."}), 400

    user_key = data.get('key', '').strip()
    user_hwid = data.get('hwid', '').strip()
    
    print(f"[*] Checking Key: '{user_key}'")
    print(f"[*] Device HWID: '{user_hwid}'")

    if not user_key or not user_hwid:
        return jsonify({"status": "error", "message": "Missing key or HWID."}), 400

    # Load the live database generated by the Telegram Bot
    history_db = read_apk_history()
    active_keys = read_active_apk_keys()

    # 1. Does the key exist at all?
    if user_key not in history_db:
        print("[!] ERROR: Key not found in Bot Database.")
        return jsonify({"status": "error", "message": "Invalid license key."}), 401

    key_info = history_db[user_key]
    current_status = key_info["status"]

    # 2. Key was deleted by Reseller/Admin
    if current_status == "DELETED":
        print("[!] ERROR: Key was revoked/deleted.")
        return jsonify({"status": "error", "message": "License key revoked."}), 401

    # 3. FIRST TIME LOGIN (Binding the HWID)
    if current_status == "UNUSED":
        # Bind it to the device
        history_db[user_key]["status"] = f"USED_BY:{user_hwid}"
        save_apk_history(history_db)

        # Remove from active/unused list so resellers can't see it anymore
        if user_key in active_keys:
            del active_keys[user_key]
            save_active_apk_keys(active_keys)

        print(f"[SUCCESS] Key {user_key} activated and bound to HWID: {user_hwid}")
        return jsonify({"status": "success", "message": "ACTIVATED & BOUND TO DEVICE"}), 200

    # 4. RETURNING USER (Checking HWID)
    if current_status.startswith("USED_BY:"):
        bound_hwid = current_status.split(":")[1]
        
        if bound_hwid == user_hwid:
            print(f"[SUCCESS] HWID MATCH. Access Granted.")
            return jsonify({"status": "success", "message": "AUTHENTICATION SUCCESSFUL"}), 200
        else:
            print(f"[WARNING] HWID MISMATCH! Bound to {bound_hwid}, but {user_hwid} tried to login.")
            return jsonify({"status": "error", "message": "KEY BOUND TO ANOTHER DEVICE"}), 403

    # Fallback
    return jsonify({"status": "error", "message": "Unknown Key Error"}), 400

if __name__ == '__main__':
    print(">>> FROZEN FIRE APK BACKEND RUNNING <<<")
    print(">>> Synced with Telegram Bot Database <<<")
    
    port = int(os.environ.get("PORT", 5000))
    app.run(host='0.0.0.0', port=port)
